apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
  labels:
    {{- include "workprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: {{ include "workprofile.fullname" . }}-db
spec:
  ports:
    - port: {{ .Values.db.service.port }} 
      targetPort: {{ .Values.db.service.name }} 
      protocol: TCP
      name: {{ .Values.db.service.name }} 
  clusterIP: None 
  selector:
    app.kubernetes.io/name: {{ include "workprofile.fullname" . }}-db 