apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "workprofile.fullname" . }}-storage
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }} 
  resources:
    requests:
      storage: {{ .Values.persistence.size }}