apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: workprofile-db
  name: workprofile-db
  namespace: workprofile
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: workprofile-db
  type: ClusterIP
status:
  loadBalancer: {}
