---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workprofile
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        - environment: staging
        - environment: production
  template:
    metadata:
      name: 'workprofile-{{.environment}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:arkos/gitops.git
        targetRevision: HEAD
        path: workprofile
        helm:
          valueFiles:
            - values-{{.environment}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: workprofile-{{.environment}}
        syncPolicy:
          automated: 
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true