---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workprofile-secret
  namespace: workprofile
spec:
  encryptedData:
    DB_PASS: AgCnqd3qvBGQ7VogPum7ZIIMkX7pZynm831nE9tDXlqKHY6GqkbFbFVgZ7Rr1bY3aW/RAFNMmO7LdgrcZFGd/Ii2oFqIQkh1Tsgp5dmfHwmbXJSZaoSphwjLpU929re7y7w/P9ueKMsTFGARZUBhvWeKNfjIDdWzNNowLJAnzLZAWSZfCJZi8ptn8bL++aI7RP+utfQUBXDfDqnYeBytpVNBaOntBo3V++lRoKzOby3RQrYcai/IYS4O9NdJ+ZF4Zys3A8l6HcVeBfytnohdSvTpPUAV4duJO3RQQVJLKfG8Zt0eM2tbFub/ZD7Ckktsg4/AxggI4sfMCQxqWxVEOLAzHmx+MrZn/kUVUhjmVjaXKczniHGLGSmMXjEFS8qywO8BuUoCLtuMqIbv7+J05h6/DlrcU+T0sOiZDYvUuNuYx2T5fo5FH+hJDcRqQX+Ovt/gM6S5oOkUv8TOylBbKhHatTx3Mg+0fYdVNgk1caTUDXXAGTXh2yjGrqulp1w8xObG9AWzJC+wLtVvZUUXIvWPijYQ1o+tDA+56hsvGigH+pBX4dOzBvmOhXR3zUOnVFj7ACLoSIjz/1fJ89fq3CXoOOmcXkoinFoUzp7mLtog9zgMybZxV87Skb5bS3U1Ei+5KhWeoJnnr58rSea7+0sr4ebWO5mgNDyOR1ApNsmg82JPA27o7Zh4uDUMlJqW1y0p96LFvjkT
    ROOT_DB_PASSWORD: AgAjATGoJ5iHS2Mlm4wMm/An7d8t3iUbHu7DWlWVsm6FwkHzMCWcBZl7gVk1KgMZbfKjw9F9VDBUCETZdawGSJsWmPnjtbn/oj0T3ze/M6/3nY0QJn6VAvgWFnM3ncoloVLjmOZYT6Zz5RYoJI2Wmr7SqcTv6m9U8M4hWJmv872oYUFWjED5mUOmRm2/KWvHTDkYcchj1fFdb1Ddum2x8ZKTtzCADCYrHYLXeleJVutiCubDIo3K2F//cBNeDjb20NbY3L0vlwfTimxe6g3zjPSYFh43IVThdrLAPGJpa2WJUDmCBD7QYfwTilwQP7NQ0wJSRVE9BTl+euLzKvAOBVly1bpJSUV68Z0WmeY5f9I+eAw/BbVQbFTZKuleNJeGY6e40lyouARf1JcycqoVvBeHs/QOvMntNVvpf3328X4ph4AvMZsGTyRSbqOQgdZEtDPZDpSJ5V2mPjOQhcZt5BeRalWgrGnScdZswfEOSO1GbIwiJ+ntQpxHpMV2FZLClYEKZpRcoI+g7HcPKNIg09BE/abw26jaREal2FyjFrkgLukDEZvMR3ZmBO0QvXjTmPfDw9Fi9xzrhxEATvPpFOrQYaw5LdjzFue5D7EF6JrrnOCkeS2GfAqJHSC2jN/dkKzAaoyd5knvpgtcJ4MJc3tQAtlRWAF+oc3f/lB6RY4Oq6RUC7VX4lgj0tlMcRd1F+StMdj3A84CJHE=
  template:
    metadata:
      creationTimestamp: null
      name: workprofile-secret
      namespace: workprofile
