apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workprofile-storage
  namespace: workprofile
spec:
  storageClassName: ebs-csi-gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi