apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workprofile
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - foo: bar
  template:
    metadata:
      name: 'workprofile-{{.foo}}'
    spec:
      destination:
        namespace: workprofile-{{.foo}}
        server: {{ .Values.spec.destination.server }}
      project: default
      source:
        path: workprofile
        repoURL: {{ .Values.spec.source.repoURL }}
        targetRevision: {{ .Values.spec.source.targetRevision }}
        helm:
          valueFiles:
            - values-{{.foo}}.yaml
      {{- if .Values.spec.syncPolicy.enabled }} # <-- New: Conditional rendering
      syncPolicy:
        automated:
          prune: {{ .Values.spec.syncPolicy.automated.prune }}
          selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}
        {{- if .Values.spec.syncPolicy.syncOptions }} # Optional: if you have sync options
        syncOptions:
          {{- toYaml .Values.spec.syncPolicy.syncOptions | nindent 6 }}
        {{- end }}
      {{- end }}